        <aside class="mainRight">
            <h1><a>CPU</a></h1>
            <ul>
                <li><a>option</a></li>
                <li><a>start</a></li>
                <li><a>pause</a></li>
                <li><a>stop</a></li>
                <li><a>create</a></li>
                <li><a>kill</a></li>
                <li><a>getThreads</a></li>
                <li><a>smartSleep</a></li>
                <li><a>log</a></li>
                <li><a>onInterval</a></li>
            </ul>
            <h1><a>Thread</a></h1>
            <ul>
                <li><a>add</a></li>
                <li><a>remove</a></li>
                <li><a>fire</a></li>
            </ul>
            <h1><a>Event</a></h1>
            <ul>
                <li><a>attach</a></li>
                <li><a>detach</a></li>
                <li><a>exc</a></li>
                <li><a>excAndDetach</a></li>
                <li><a>Level</a></li>
            </ul>
            <h1><a>Cookie</a></h1>
            <ul>
                <li><a>getCookieObj</a></li>
                <li><a>get</a></li>
                <li><a>set</a></li>
            </ul>
            <h1><a>Breathe</a></h1>
            <ul>
                <li><a>fromJson</a></li>
                <li><a>addJs</a></li>
                <li><a>jsonp</a></li>
                <li><a>joinParam</a></li>
                <li><a>ajax</a></li>
                <li><a>require</a></li>
                <li><a>combine</a></li>
                <li><a>addEvent</a></li>
                <li><a>removeEvent</a></li>
                <li><a>addIFrame</a></li>
            </ul>
        </aside>